# Create a random tensor with shape (7, 7)

In [2]:
import torch 
import numpy as np

In [3]:
# Creat Random Tensor ...
tensor_1 = torch.rand(size =(7,7))

In [4]:
tensor_1

tensor([[0.2094, 0.3104, 0.5641, 0.0035, 0.7899, 0.9238, 0.4499],
        [0.1014, 0.0332, 0.2723, 0.5794, 0.4612, 0.3347, 0.2384],
        [0.7951, 0.8973, 0.2967, 0.7956, 0.3804, 0.6375, 0.1313],
        [0.7511, 0.4475, 0.6812, 0.6114, 0.8292, 0.9834, 0.5887],
        [0.8787, 0.5494, 0.8694, 0.7180, 0.6637, 0.4444, 0.7543],
        [0.1137, 0.3403, 0.1631, 0.8226, 0.1657, 0.2171, 0.2418],
        [0.1878, 0.8170, 0.9274, 0.8557, 0.7375, 0.5730, 0.2549]])

In [10]:
tensor_2 = tensor_1 * 10  # Addition
tensor_2

tensor([[2.0936, 3.1042, 5.6405, 0.0346, 7.8990, 9.2376, 4.4989],
        [1.0144, 0.3321, 2.7231, 5.7940, 4.6118, 3.3474, 2.3837],
        [7.9505, 8.9726, 2.9674, 7.9556, 3.8042, 6.3749, 1.3128],
        [7.5108, 4.4748, 6.8118, 6.1142, 8.2924, 9.8344, 5.8872],
        [8.7873, 5.4939, 8.6936, 7.1804, 6.6368, 4.4438, 7.5434],
        [1.1373, 3.4029, 1.6308, 8.2261, 1.6565, 2.1705, 2.4184],
        [1.8781, 8.1702, 9.2738, 8.5566, 7.3751, 5.7297, 2.5494]])

### Perform a matrix multiplication on the tensor_1 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [11]:
tensor_3 = torch.rand(size=(1,7))
tensor_3 @ tensor_1

tensor([[1.3159, 1.4174, 1.8063, 1.4095, 2.0082, 2.1706, 1.3095]])

In [12]:
tensor_1 @ tensor_3.T

tensor([[1.0423],
        [0.8937],
        [1.7656],
        [2.1011],
        [2.2159],
        [0.9167],
        [1.5062]])

In [13]:
torch.matmul(tensor_3,tensor_1)

tensor([[1.3159, 1.4174, 1.8063, 1.4095, 2.0082, 2.1706, 1.3095]])

###  Set the random seed to 0 and do 2 & 3 over again.

In [47]:
import torch

# Set manual seed
random = 0
# Create two random tensors
torch.manual_seed(random)
tensor_A = torch.rand(size = (7,7))
print("tensor_A :\n " , tensor_A)

torch.manual_seed(random)
tensor_B = torch.rand(size=(7,1))
print("tensor_B :\n " , tensor_B)

# Matrix multiply tensors
output =  tensor_A @ tensor_B
print("Output : \n ", output, output.shape)

tensor_A :
  tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor_B :
  tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
Output : 
  tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) torch.Size([7, 1])


### find max, min, argmax, argmin

In [49]:
torch.max(output)

tensor(1.6838)

In [50]:
torch.min(output)

tensor(0.8279)

In [51]:
torch.argmin(output)

tensor(4)

In [52]:
torch.argmax(output)

tensor(3)

### Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [65]:
# Set seed
random =  7

# Create random tensor
torch.manual_seed(random)
tensor_C = torch.rand(size  = (1,1,1,10))

# Remove single dimensions
tensor_D = tensor_C.squeeze()

# Print out tensors and their shapes
print("tensor_C : " , tensor_C)
print("tensor_D : " , tensor_D)

tensor_C :  tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor_D :  tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


## Create a straight line dataset using the linear regression formula (weight * X + bias).